-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 15:39:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsysab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsysab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsysab` DEFAULT CHARACTER SET utf8 ;
USE `dbsysab` ;

-- -----------------------------------------------------
-- Table `dbsysab`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `localidade` VARCHAR(100) NULL,
  `UF` VARCHAR(10) NULL,
  `cod_pais` VARCHAR(20) NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`proprietario` (
  `idproprietario` INT NOT NULL AUTO_INCREMENT,
  `idmunicipio` INT NULL,
  `tipo_pessoa` VARCHAR(20) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `fantasia` VARCHAR(100) NULL,
  `fisica_juridica` VARCHAR(15) NULL,
  `cpf_cnpj` VARCHAR(30) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `complemento_end` VARCHAR(100) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `uf` VARCHAR(5) NULL,
  `cep` VARCHAR(20) NULL,
  `referencia` VARCHAR(256) NULL,
  `obs_prop` VARCHAR(512) NULL,
  `rg_ie` VARCHAR(20) NULL,
  `condicao` VARCHAR(20) NULL,
  `conjuge` VARCHAR(50) NULL,
  `aos_cuidados` VARCHAR(100) NULL,
  `end_corr` VARCHAR(100) NULL,
  `num_corr` VARCHAR(15) NULL,
  `compl_corr` VARCHAR(100) NULL,
  `bairro_corr` VARCHAR(45) NULL,
  `cidade_corr` VARCHAR(45) NULL,
  `uf_corr` VARCHAR(5) NULL,
  `cep_corr` VARCHAR(20) NULL,
  `favorecido` VARCHAR(100) NULL,
  `cpf_fav` VARCHAR(20) NULL,
  `banco_fav` VARCHAR(10) NULL,
  `ag_fav` VARCHAR(10) NULL,
  `conta_fav` VARCHAR(45) NULL,
  PRIMARY KEY (`idproprietario`),
  INDEX `fk_pessoa_municipio_idx` (`idmunicipio` ASC),
  CONSTRAINT `fk_pessoa_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `dbsysab`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`imovel` (
  `idimovel` INT NOT NULL AUTO_INCREMENT,
  `idproprietario` INT NULL,
  `idmunicipio` INT NULL,
  `nome` VARCHAR(256) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `complemento` VARCHAR(256) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `uf` VARCHAR(5) NULL,
  `cep` VARCHAR(20) NULL,
  `referencia` VARCHAR(256) NULL,
  `obs` VARCHAR(512) NULL,
  `condicao` VARCHAR(20) NULL,
  `codigo` VARCHAR(45) NULL,
  `situacao` VARCHAR(45) NULL,
  `idinquilino` INT NULL,
  `idlocacao` INT NULL,
  PRIMARY KEY (`idimovel`),
  INDEX `fk_pessoa_municipio_idx` (`idmunicipio` ASC),
  INDEX `fk_imovel_proprietario_idx` (`idproprietario` ASC),
  CONSTRAINT `fk_imovel_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `dbsysab`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_proprietario`
    FOREIGN KEY (`idproprietario`)
    REFERENCES `dbsysab`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`inquilino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`inquilino` (
  `idinquilino` INT NOT NULL AUTO_INCREMENT,
  `idproprietario` INT NULL,
  `idimovel` INT NULL,
  `idmunicipio` INT NULL,
  `tipo_pessoa` VARCHAR(20) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `fantasia` VARCHAR(100) NULL,
  `fisica_juridica` VARCHAR(15) NULL,
  `cpf_cnpj` VARCHAR(30) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `complemento` VARCHAR(100) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `uf` VARCHAR(5) NULL,
  `cep` VARCHAR(20) NULL,
  `referencia` VARCHAR(256) NULL,
  `obs` VARCHAR(512) NULL,
  `rg_ie` VARCHAR(20) NULL,
  `condicao` VARCHAR(20) NULL,
  `conjuge` VARCHAR(50) NULL,
  `aos_cuidados` VARCHAR(100) NULL,
  `end_corr` VARCHAR(100) NULL,
  `num_corr` VARCHAR(15) NULL,
  `compl_corr` VARCHAR(100) NULL,
  `bairro_corr` VARCHAR(45) NULL,
  `cidade_corr` VARCHAR(45) NULL,
  `uf_corr` VARCHAR(5) NULL,
  `cep_corr` VARCHAR(20) NULL,
  `favorecido` VARCHAR(100) NULL,
  `cpf_fav` VARCHAR(20) NULL,
  `banco_fav` VARCHAR(10) NULL,
  `ag_fav` VARCHAR(10) NULL,
  `conta_fav` VARCHAR(45) NULL,
  `ult_extrato` DECIMAL(10,0) NULL,
  `data_ult_extrato` DATETIME NULL,
  `irrf` VARCHAR(10) NULL,
  `locacao_encerada` VARCHAR(10) NULL,
  `dt_enc_locacao` DATETIME NULL,
  `ult_recibo` VARCHAR(10) NULL,
  `idlocacao` INT NULL,
  PRIMARY KEY (`idinquilino`),
  INDEX `fk_pessoa_municipio_idx` (`idmunicipio` ASC),
  INDEX `fk_inquilino_proprietario_idx` (`idproprietario` ASC),
  INDEX `fk_inquilino_imovel_idx` (`idimovel` ASC),
  CONSTRAINT `fk_inquilino_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `dbsysab`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquilino_proprietario`
    FOREIGN KEY (`idproprietario`)
    REFERENCES `dbsysab`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquilino_imovel`
    FOREIGN KEY (`idimovel`)
    REFERENCES `dbsysab`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`fiador` (
  `idfiador` INT NOT NULL AUTO_INCREMENT,
  `idinquilino` INT NULL,
  `idmunicipio` INT NULL,
  `tipo_pessoa` VARCHAR(20) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `fantasia` VARCHAR(100) NULL,
  `fisica_juridica` VARCHAR(15) NULL,
  `cpf_cnpj` VARCHAR(30) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `complemento` VARCHAR(100) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `uf` VARCHAR(5) NULL,
  `cep` VARCHAR(20) NULL,
  `referencia` VARCHAR(256) NULL,
  `obs` VARCHAR(512) NULL,
  `rg_ie` VARCHAR(20) NULL,
  `condicao` VARCHAR(20) NULL,
  `conjuge` VARCHAR(50) NULL,
  `aos_cuidados` VARCHAR(100) NULL,
  `end_corr` VARCHAR(100) NULL,
  `num_corr` VARCHAR(15) NULL,
  `compl_corr` VARCHAR(100) NULL,
  `bairro_corr` VARCHAR(45) NULL,
  `cidade_corr` VARCHAR(45) NULL,
  `uf_corr` VARCHAR(5) NULL,
  `cep_corr` VARCHAR(20) NULL,
  PRIMARY KEY (`idfiador`),
  INDEX `fk_pessoa_municipio_idx` (`idmunicipio` ASC),
  INDEX `fk_fiador_inquilino_idx` (`idinquilino` ASC),
  CONSTRAINT `fk_fiador_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `dbsysab`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiador_inquilino`
    FOREIGN KEY (`idinquilino`)
    REFERENCES `dbsysab`.`inquilino` (`idinquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`indice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`indice` (
  `idindice` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idindice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`lacto_indice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`lacto_indice` (
  `idlacto_indice` INT NOT NULL AUTO_INCREMENT,
  `idindice` INT NULL,
  `mes_ano` VARCHAR(20) NOT NULL,
  `valor` DECIMAL(4,4) NULL,
  PRIMARY KEY (`idlacto_indice`),
  INDEX `fk_lacto_indice_indice_idx` (`idindice` ASC),
  CONSTRAINT `fk_lacto_indice_indice`
    FOREIGN KEY (`idindice`)
    REFERENCES `dbsysab`.`indice` (`idindice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`reajuste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`reajuste` (
  `idreajuste` INT NOT NULL AUTO_INCREMENT,
  `idindice` INT NULL,
  `mes_ano` VARCHAR(20) NOT NULL,
  `mensal` DECIMAL(10,4) NULL,
  `bimestral` DECIMAL(10,4) NULL,
  `trimestral` DECIMAL(10,4) NULL,
  `quadrimestral` DECIMAL(10,4) NULL,
  `quintimestral` DECIMAL(10,4) NULL,
  `semestral` DECIMAL(10,4) NULL,
  `anual` DECIMAL(10,4) NULL,
  `bianual` DECIMAL(10,4) NULL,
  PRIMARY KEY (`idreajuste`),
  INDEX `fk_reajuste_indice_idx` (`idindice` ASC),
  CONSTRAINT `fk_reajuste_indice`
    FOREIGN KEY (`idindice`)
    REFERENCES `dbsysab`.`indice` (`idindice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `comissao` VARCHAR(10) NULL,
  `pede_qtde` VARCHAR(10) NULL,
  `unidade` VARCHAR(20) NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `incide_cc` VARCHAR(10) NULL,
  `irrf` VARCHAR(10) NULL,
  `imp_recibo` VARCHAR(10) NULL,
  `cont_c_deb_cred` VARCHAR(10) NULL,
  `comissao_iptu` VARCHAR(10) NULL,
  `libera_cc` VARCHAR(10) NULL,
  `agrupamento` VARCHAR(45) NULL,
  `boleto` VARCHAR(10) NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`locacao` (
  `idlocacao` INT NOT NULL AUTO_INCREMENT,
  `idinquilino` INT NULL,
  `idproprietario` INT NULL,
  `idimovel` INT NULL,
  `idindice` INT NULL,
  `dt_inicial` DATETIME NULL,
  `dt_final` DATETIME NULL,
  `reajuste` INT NULL,
  `contador_aluguel` INT NULL,
  `reajuste_sobre` DECIMAL(10,2) NULL,
  `vencimento` DATETIME NULL,
  `taxa_adm` DECIMAL(10,2) NULL,
  `desocupacao` DATETIME NULL,
  `estado` VARCHAR(10) NULL,
  `mes_ano` VARCHAR(10) NULL,
  `dt_ini_contrato` DATETIME NULL,
  `dt_fin_contrato` DATETIME NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idlocacao`),
  INDEX `fk_locacao_iniquilino_idx` (`idinquilino` ASC),
  INDEX `fk_locacao_prorietario_idx` (`idproprietario` ASC),
  INDEX `fk_locacao_imovel_idx` (`idimovel` ASC),
  INDEX `fk_locacao_indice_idx` (`idindice` ASC),
  CONSTRAINT `fk_locacao_iniquilino`
    FOREIGN KEY (`idinquilino`)
    REFERENCES `dbsysab`.`inquilino` (`idinquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_prorietario`
    FOREIGN KEY (`idproprietario`)
    REFERENCES `dbsysab`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_imovel`
    FOREIGN KEY (`idimovel`)
    REFERENCES `dbsysab`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_indice`
    FOREIGN KEY (`idindice`)
    REFERENCES `dbsysab`.`indice` (`idindice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`detalhe_locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`detalhe_locacao` (
  `iddetalhe_locacao` INT NOT NULL AUTO_INCREMENT,
  `idlocacao` INT NULL,
  `idevento` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `qtde` VARCHAR(10) NULL,
  `valor` DECIMAL(10,2) NULL,
  `mes_ano_det` VARCHAR(10) NULL,
  `qtde_limite` VARCHAR(10) NULL,
  PRIMARY KEY (`iddetalhe_locacao`),
  INDEX `fk_detalhe_loc_locacao_idx` (`idlocacao` ASC),
  INDEX `fk_detalhe_loca_evento_idx` (`idevento` ASC),
  CONSTRAINT `fk_detalhe_loc_locacao`
    FOREIGN KEY (`idlocacao`)
    REFERENCES `dbsysab`.`locacao` (`idlocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhe_loca_evento`
    FOREIGN KEY (`idevento`)
    REFERENCES `dbsysab`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`recibo` (
  `idrecibo` INT NOT NULL AUTO_INCREMENT,
  `idlocacao` INT NULL,
  `mes_ano` VARCHAR(10) NOT NULL,
  `dt_inicial` DATETIME NULL,
  `dt_final` DATETIME NULL,
  `contador_aluguel` INT NULL,
  `reajuste` INT NULL,
  `dt_vencimento` DATETIME NULL,
  `dt_pagamento` DATETIME NULL,
  `idremessa` INT NULL,
  `nosso_numero` VARCHAR(45) NULL,
  `forma_pgto` VARCHAR(20) NULL,
  `cheque` VARCHAR(10) NULL,
  `banco` VARCHAR(10) NULL,
  `praca` VARCHAR(10) NULL,
  `dt_emissao` DATETIME NULL,
  `dt_apresentacao` DATETIME NULL,
  `emitente` VARCHAR(100) NULL,
  `valor_pgto` DECIMAL(10,2) NULL,
  `troco` DECIMAL(10,2) NULL,
  `telefone` VARCHAR(45) NULL,
  `obs` VARCHAR(100) NULL,
  `total_aluguel` DECIMAL(10,2) NULL,
  `estado` VARCHAR(20) NULL,
  `codigo` VARCHAR(45) NULL,
  `taxa_adm` DECIMAL(10,2) NULL,
  `liquido` DECIMAL(10,2) NULL,
  `idretorno` INT NULL,
  `idinquilino` INT NULL,
  `idproprietario` INT NULL,
  `idimovel` INT NULL,
  `idindice` INT NULL,
  PRIMARY KEY (`idrecibo`),
  INDEX `fk_recibo_locacao_idx` (`idlocacao` ASC),
  CONSTRAINT `fk_recibo_locacao`
    FOREIGN KEY (`idlocacao`)
    REFERENCES `dbsysab`.`locacao` (`idlocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`detalhe_recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`detalhe_recibo` (
  `iddetalhe_recibo` INT NOT NULL AUTO_INCREMENT,
  `idrecibo` INT NULL,
  `idevento` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `qtde` VARCHAR(10) NULL,
  `valor` DECIMAL(10,2) NULL,
  `mes_ano_det` VARCHAR(10) NULL,
  `qtde_limite` VARCHAR(10) NULL,
  PRIMARY KEY (`iddetalhe_recibo`),
  INDEX `fk_dt_recibo_recibo_idx` (`idrecibo` ASC),
  INDEX `fk_dt_recibo_evento_idx` (`idevento` ASC),
  CONSTRAINT `fk_dt_recibo_recibo`
    FOREIGN KEY (`idrecibo`)
    REFERENCES `dbsysab`.`recibo` (`idrecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dt_recibo_evento`
    FOREIGN KEY (`idevento`)
    REFERENCES `dbsysab`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `fantasia` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(5) NULL,
  `cep` VARCHAR(10) NULL,
  `cnpj` VARCHAR(30) NULL,
  `responsavel` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `creci` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `banco_padrao_boleto` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsysab`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsysab`.`banco` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `idempresa` INT NULL,
  `codigo` VARCHAR(20) NULL,
  `nome` VARCHAR(45) NULL,
  `agencia` VARCHAR(20) NULL,
  `digito_agencia` VARCHAR(10) NULL,
  `conta` VARCHAR(45) NULL,
  `digito_conta` VARCHAR(10) NULL,
  `carteira` VARCHAR(15) NULL,
  `multa` DECIMAL(4,2) NULL,
  `juros` DECIMAL(4,2) NULL,
  `jurosapos` DECIMAL(4,2) NULL,
  `prazo_protesto` VARCHAR(5) NULL,
  `logo` VARCHAR(45) NULL,
  `desc_demonstrativo1` VARCHAR(45) NULL,
  `desc_demonstrativo2` VARCHAR(45) NULL,
  `desc_demonstrativo3` VARCHAR(45) NULL,
  `instrucao1` VARCHAR(45) NULL,
  `instrucao2` VARCHAR(45) NULL,
  `instrucao3` VARCHAR(45) NULL,
  `codigo_cliente` VARCHAR(45) NULL,
  `tipo_inscr_empresa` VARCHAR(10) NULL,
  `nro_inscr_empresa` VARCHAR(45) NULL,
  `cod_convenio_banco` VARCHAR(45) NULL,
  `sequencia` INT NULL,
  `versao` VARCHAR(10) NULL,
  `tipo_arquivo` VARCHAR(10) NULL,
  `idremessa` INT NULL,
  `idretorno` INT NULL,
  `nosso_numero` VARCHAR(45) NULL,
  `ambiente` VARCHAR(10) NULL,
  `cod_cedente` VARCHAR(10) NULL,
  `path_remessa` VARCHAR(45) NULL,
  `path_retorno` VARCHAR(45) NULL,
  `prefixo_cooperativa` VARCHAR(45) NULL,
  `digito_prefixo` VARCHAR(5) NULL,
  `especie_titulo` VARCHAR(10) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `byte_idt` VARCHAR(10) NULL,
  `posto` VARCHAR(20) NULL,
  PRIMARY KEY (`idbanco`),
  INDEX `fk_banco_empresa_idx` (`idempresa` ASC),
  CONSTRAINT `fk_banco_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `dbsysab`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
